# Generated by Django 4.0 on 2021-12-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_time', models.TimeField()),
                ('booked_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('table_num', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('guests_num', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')])),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Booked')], default=0)),
                ('used_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_books', to='auth.user')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
