# Generated by Django 4.0 on 2021-12-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='menu_type',
            field=models.IntegerField(choices=[(0, ''), (1, 'Lunch'), (2, 'Dinner')], default=0),
        ),
    ]
