# Generated by Django 4.0 on 2021-12-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_testforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='testforms',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date:'),
        ),
    ]
