# Generated by Django 4.0 on 2021-12-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_testforms_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testforms',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
