# Generated by Django 4.0 on 2021-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_testforms_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testforms',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
