# Generated by Django 4.0 on 2022-01-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_testforms_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestForms',
        ),
    ]
