# Generated by Django 4.0 on 2022-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_delete_testforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='menu_type',
            field=models.IntegerField(choices=[(1, 'Lunch'), (2, 'Dinner')], default=0),
        ),
    ]
