# Generated by Django 4.0 on 2022-01-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='menu_type',
            field=models.IntegerField(choices=[(0, 'Not assigned'), (1, 'Lunch'), (2, 'Dinner')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Booked')], default=0),
        ),
    ]
