# Generated by Django 4.0 on 2022-01-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_book_updated_on_alter_book_menu_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='table_num',
            field=models.IntegerField(choices=[(0, 'Not assigned'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0),
        ),
    ]
