# Generated by Django 3.2 on 2022-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_book_used_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='menu_type',
            field=models.IntegerField(choices=[(0, 'Lunch or Dinner>'), (1, 'Lunch'), (2, 'Dinner')], default=0),
        ),
    ]
