# Generated by Django 4.0 on 2021-12-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(0, 'Dessert'), (0, 'Starter'), (0, 'Main Course')]),
        ),
    ]
