# Generated by Django 4.0 on 2021-12-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_item_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='meny_category',
        ),
    ]
