# Generated by Django 4.0 on 2021-12-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_item_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(0, 'Dessert'), (0, 'Main Course'), (0, 'Starter')], default=0),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='menu_category',
            field=models.IntegerField(choices=[(1, 'Dinner'), (0, 'Lunch')], default=0),
        ),
    ]
