# Generated by Django 4.0 on 2021-12-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_item_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(0, 'Main Course'), (0, 'Dessert'), (0, 'Starter')], default=0),
        ),
    ]
