# Generated by Django 4.0 on 2022-01-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_alter_menu_item_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(0, 'Dessert'), (0, 'Starter'), (0, 'Main Course')]),
        ),
    ]
