# Generated by Django 4.0 on 2022-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_menu_item_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(2, 'Dessert'), (0, 'Starter'), (1, 'Main Course')]),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='menu_category',
            field=models.IntegerField(choices=[(0, 'Lunch'), (1, 'Dinner')], default=0),
        ),
    ]
