# Generated by Django 4.0 on 2022-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_alter_menu_item_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(0, 'Starter'), (2, 'Dessert'), (1, 'Main Course')]),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='menu_category',
            field=models.IntegerField(choices=[(0, 'Lunch'), (1, 'Dinner')], default=0),
        ),
    ]
