# Generated by Django 4.0 on 2022-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_alter_menu_item_components_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='menu_category',
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(1, 'Main Course'), (2, 'Dessert'), (0, 'Starter')]),
        ),
    ]
