# Generated by Django 4.0 on 2022-01-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_remove_menu_item_menu_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(2, 'Dessert'), (0, 'Starter'), (1, 'Main Course')]),
        ),
    ]
