# Generated by Django 4.0 on 2022-01-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_alter_menu_item_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_category',
            field=models.IntegerField(choices=[(2, 'Dessert'), (0, 'Starter'), (1, 'Main Course')]),
        ),
    ]
